"""Ubah nullable jadi true di tabel administrator.

Revision ID: 04c497e4e573
Revises: 97dda21ac1f0
Create Date: 2025-04-28 22:38:00.173018

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '04c497e4e573'
down_revision = '97dda21ac1f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('administrators', schema=None) as batch_op:
        batch_op.alter_column('no_wa',
               existing_type=mysql.VARCHAR(length=250),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('administrators', schema=None) as batch_op:
        batch_op.alter_column('no_wa',
               existing_type=mysql.VARCHAR(length=250),
               nullable=False)

    # ### end Alembic commands ###
