"""edit model users

Revision ID: 44469d804de5
Revises: a339aa23e919
Create Date: 2025-04-11 19:24:38.399802

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '44469d804de5'
down_revision = 'a339aa23e919'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('no_wa',
               existing_type=mysql.VARCHAR(length=250),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('no_wa',
               existing_type=mysql.VARCHAR(length=250),
               nullable=False)

    # ### end Alembic commands ###
