"""tambah kolom number_pothole di tabel report_pothole.

Revision ID: 5b2e4b5ce527
Revises: 44469d804de5
Create Date: 2025-04-25 17:48:31.873647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b2e4b5ce527'
down_revision = '44469d804de5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pothole_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('number_potholes', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pothole_reports', schema=None) as batch_op:
        batch_op.drop_column('number_potholes')

    # ### end Alembic commands ###
