"""tambah kolom address di tabel report_pothole.

Revision ID: 97dda21ac1f0
Revises: 5b2e4b5ce527
Create Date: 2025-04-25 22:18:13.521010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97dda21ac1f0'
down_revision = '5b2e4b5ce527'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pothole_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(length=250), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pothole_reports', schema=None) as batch_op:
        batch_op.drop_column('address')

    # ### end Alembic commands ###
