"""Initial migration2

Revision ID: a339aa23e919
Revises: 
Create Date: 2025-04-10 21:22:17.358068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a339aa23e919'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('administrators',
    sa.Column('administrator_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('no_wa', sa.String(length=250), nullable=False),
    sa.Column('username', sa.String(length=250), nullable=False),
    sa.Column('password', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('administrator_id')
    )
    with op.batch_alter_table('administrators', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_administrators_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_administrators_no_wa'), ['no_wa'], unique=True)

    op.create_table('users',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('no_wa', sa.String(length=250), nullable=False),
    sa.Column('username', sa.String(length=250), nullable=False),
    sa.Column('password', sa.String(length=250), nullable=False),
    sa.Column('status', sa.Integer(), server_default='1', nullable=False, comment='0: Tidak Aktif, 1: Aktif'),
    sa.PrimaryKeyConstraint('user_id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_no_wa'), ['no_wa'], unique=True)

    op.create_table('pothole_reports',
    sa.Column('pothole_report_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('administrator_id', sa.Integer(), nullable=True),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.Column('latitude', sa.DECIMAL(precision=10, scale=8), nullable=False),
    sa.Column('longtitude', sa.DECIMAL(precision=11, scale=8), nullable=False),
    sa.Column('image', sa.String(length=250), nullable=False),
    sa.Column('status', sa.Enum('selesai', 'proses', 'ditolak', name='status_report'), nullable=False),
    sa.ForeignKeyConstraint(['administrator_id'], ['administrators.administrator_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('pothole_report_id')
    )
    op.create_table('surveyors',
    sa.Column('surveyor_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('administrator_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('no_wa', sa.String(length=250), nullable=False),
    sa.Column('username', sa.String(length=250), nullable=False),
    sa.Column('password', sa.String(length=250), nullable=False),
    sa.ForeignKeyConstraint(['administrator_id'], ['administrators.administrator_id'], ),
    sa.PrimaryKeyConstraint('surveyor_id')
    )
    with op.batch_alter_table('surveyors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_surveyors_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_surveyors_no_wa'), ['no_wa'], unique=True)

    op.create_table('pothole_segments',
    sa.Column('pothole_segment_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('surveyor_id', sa.Integer(), nullable=True),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.Column('latitude_awal', sa.DECIMAL(precision=10, scale=8), nullable=False),
    sa.Column('longtitude_awal', sa.DECIMAL(precision=11, scale=8), nullable=False),
    sa.Column('latitude_akhir', sa.DECIMAL(precision=10, scale=8), nullable=False),
    sa.Column('longtitude_akhir', sa.DECIMAL(precision=11, scale=8), nullable=False),
    sa.Column('number_potholes', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['surveyor_id'], ['surveyors.surveyor_id'], ),
    sa.PrimaryKeyConstraint('pothole_segment_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pothole_segments')
    with op.batch_alter_table('surveyors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_surveyors_no_wa'))
        batch_op.drop_index(batch_op.f('ix_surveyors_name'))

    op.drop_table('surveyors')
    op.drop_table('pothole_reports')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_no_wa'))
        batch_op.drop_index(batch_op.f('ix_users_name'))

    op.drop_table('users')
    with op.batch_alter_table('administrators', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_administrators_no_wa'))
        batch_op.drop_index(batch_op.f('ix_administrators_name'))

    op.drop_table('administrators')
    # ### end Alembic commands ###
