"""tambah kolom pesan di tabel pothole_repors

Revision ID: c84d64036c61
Revises: eec5aa67f6d0
Create Date: 2025-05-20 17:03:09.705209

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c84d64036c61'
down_revision = 'eec5aa67f6d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pothole_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pesan', mysql.LONGTEXT(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pothole_reports', schema=None) as batch_op:
        batch_op.drop_column('pesan')

    # ### end Alembic commands ###
