"""tambah kolom kecamatan di tabel pohtol_reports.

Revision ID: cb79282c5026
Revises: 04c497e4e573
Create Date: 2025-05-06 18:58:00.076419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb79282c5026'
down_revision = '04c497e4e573'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pothole_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kecamatan', sa.String(length=250), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pothole_reports', schema=None) as batch_op:
        batch_op.drop_column('kecamatan')

    # ### end Alembic commands ###
