"""tambah kolom status di tabel administrators.

Revision ID: eec5aa67f6d0
Revises: cb79282c5026
Create Date: 2025-05-06 22:42:51.597226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eec5aa67f6d0'
down_revision = 'cb79282c5026'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('administrators', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Integer(), server_default='1', nullable=False, comment='0: Tidak Aktif, 1: Aktif'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('administrators', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
